### ISSUE TITLE
" " when not in home region - owntracks template

### ISSUE THREAD

**Issue by JtwoA** [dbochicchio/reactor-mqtt-contrib#1]
Is this the expected outcome if someone is away from their home region/not in a defined region?

![image](https://user-images.githubusercontent.com/12992040/208763048-dda76cee-5f94-4edc-ad37-005c3553f912.png)

**Comment by dbochicchio** [comment]
the screenshot is not visible. can you please elaborate? thanks.

**Comment by JtwoA** [comment]
Yeah, sure.  When in the home Region of `Home` you see "Home" displayed in MSR Entities.  When leaving your home Region and not entering any other named region you see "" with no text.  Would expect "not_home" or something to that effect vs a blank.  Some automations can be driven from a non-location of "not_home".

**Comment by dbochicchio** [comment]
oh, this could be added as an option. I don't want to break the existing template. watch out for a future release in the upcoming days.

**Comment by dbochicchio** [comment]
@JtwoA it's now fully supported under the new templates. download the file, replace it, restart reactor and give it a try! thanks!
